{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "a0b8bb1f_a5955f99",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 5050
      },
      "writtenOn": "2022-02-16T13:35:16Z",
      "side": 1,
      "message": "The Kokoro failure is a flake on gcp_windows_reactor_llvm. All other bots passed.",
      "revId": "b68050b01d242fa45cb9d57f9a9da7eb47beebc7",
      "serverId": "aea13c4a-0b89-3eca-aee9-e193b1b77aa4"
    }
  ]
}